<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\css\images\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="MySql.Data" Version="9.7.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdministraciondePersonal.Entities\AdministraciondePersonal.Entities.csproj" />
    <ProjectReference Include="..\AdministraciondePersonal.Repository\AdministraciondePersonal.Repository.csproj" />
    <ProjectReference Include="..\AdministraciondePersonal.Services\AdministraciondePersonal.Services.csproj" />
  </ItemGroup>

</Project>
